import { keysType } from './types'

export const keys: keysType = {
  '`': {label: '`', htmlTitle:  '0', function:  0}, 
  '1': {label: '1', htmlTitle:  '1', function:  1}, 
  '2': {label: '2', htmlTitle:  '2', function:  2}, 
  '3': {label: '3', htmlTitle:  '3', function:  3}, 
  '4': {label: '4', htmlTitle:  '4', function:  4}, 
  '5': {label: '5', htmlTitle:  '5', function:  5}, 
  '6': {label: '6', htmlTitle:  '6', function:  6}, 
  '7': {label: '7', htmlTitle:  '7', function:  7}, 
  '8': {label: '8', htmlTitle:  '8', function:  8}, 
  '9': {label: '9', htmlTitle:  '9', function:  9}, 
  '0': {label: '0', htmlTitle: '10', function: 10},
  'q': {label: 'q', htmlTitle: 'sine'    , function: 'sine'}, 
  'w': {label: 'w', htmlTitle: 'triangle', function: 'triangle'}, 
  'e': {label: 'e', htmlTitle: 'sawtooth', function: 'sawtooth'}, 
  'r': {label: 'r', htmlTitle: 'square'  , function: 'square'}, 
  's': {label: 's', htmlTitle: 'C#', function: '17.32', type: 'note'}, 
  'd': {label: 'd', htmlTitle: 'D#', function: '19.45', type: 'note'}, 
  'g': {label: 'g', htmlTitle: 'F#', function: '23.12', type: 'note'}, 
  'h': {label: 'h', htmlTitle: 'G#', function: '25.96', type: 'note'}, 
  'j': {label: 'j', htmlTitle: 'A#', function: '29.14', type: 'note'}, 
  'z': {label: 'z', htmlTitle: 'C', function: '16.35', type: 'note'}, 
  'x': {label: 'x', htmlTitle: 'D', function: '18.35', type: 'note'}, 
  'c': {label: 'c', htmlTitle: 'E', function: '20.60', type: 'note'}, 
  'v': {label: 'v', htmlTitle: 'F', function: '21.83', type: 'note'}, 
  'b': {label: 'b', htmlTitle: 'G', function: '24.50', type: 'note'}, 
  'n': {label: 'n', htmlTitle: 'A', function: '27.50', type: 'note'}, 
  'm': {label: 'm', htmlTitle: 'B', function: '30.87', type: 'note'}, 
  ',': {label: ',', htmlTitle: 'C', function: '32.70', type: 'note'}
} 
